spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/rafeeq
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=bXktdmVyeS1zZWNyZXQta2V5LWZvci1yYWZlZXEtYXBwbGljYXRpb24tMTIzNDU2Nzg5MDEyMzQ1Ng==
jwt.expiration=86400000
jwt.refresh-expiration=2592000000

server.port=8080